---
- name: Add insync GPG Key
  shell: "rpm --import https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key"
  sudo: True

- name: Add insync yum repo
  copy:
    dest: /etc/yum.repos.d/insync.repo
    owner: root
    group: root
    mode: 0644
    content: |
      [insync]
      name=insync repo
      baseurl=http://yum.insynchq.com/fedora/$releasever/
      gpgcheck=1
      gpgkey=https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
      enabled=1
      repo_gpgcheck=1
      metadata_expire=120m
  sudo: True

- name: Install some devel software
#  dnf:
#    name: "{{ item }}"
#    state: present
  shell: "dnf install -y {{ item }}"
  sudo: True
  with_items:
    - insync
