---
- include: devel.yml

- include: vim.yml

- include: insync.yml

- include: modem.yml

- include: virt-manager.yml

- name: Install some more software
#  dnf:
#    name: "{{ item }}"
#    state: present
  shell: "dnf install -y {{ item }}"
  sudo: True
  with_items:
    - qbittorrent
    - quassel-client
    - sshpass

- git:
    repo: "https://github.com/Fale/fale.github.io.git"
    dest: /home/fale/faleBlog
    track_submodules: True
    force: True
  sudo: True

- file:
    name: /home/fale/faleBlog
    state: directory
    owner: fale
    group: fale
  sudo: True
