---
- name: Install some more software
#  dnf:
#    name: "{{ item }}"
#    state: present
  shell: "dnf install -y {{ item }}"
  sudo: True
  with_items:
    - qbittorrent
    - quassel
    - sshpass
