---
- name: Install virt-manager software
#  dnf:
#    name: "{{ item }}"
#    state: present
  shell: "dnf install -y {{ item }}"
  sudo: True
  with_items:
    - virt-manager
    - libvirt-daemon-kvm
    - libvirt-daemon-config-network

- name: Run the libvirt daemon
  service:
    name: libvirtd
    state: started
    enabled: True
